Create argument to sort AIPs
artefactual/fixity pull request #50
Opened 2024-09-24 17:52 UTC by Dhwaniartefact

This PR creates an argument `--sort` to display the results of fixity check error messages on top and success messages below.

Connected to https://github.com/archivematica/Issues/issues/1681

2024-09-24 18:01 UTC, replaceafill requested changes
This looks good @Dhwaniartefact, but I think we should extend that new test case to assert it's actually separating errors and successes as you describe.

2024-09-24 18:01 UTC, replaceafill commented on tests/test_fixity.py
> +            "Successfully scanned 2 AIPs",
Could you please add a couple of errors to this test case? Something along the lines of:

* Fixity scan of aip1 succeeds
* Fixity scan of aip2 fails
* Fixity scan of aip3 succeeds
* Fixity scan of aip4 fails

And check the output should list them as:

* Fixity scan of aip2 failed
* Fixity scan of aip4 failed
* Fixity scan of aip1 succeeded
* Fixity scan of aip3 succeeded
* Successfully scanned 4 AIPs

2024-09-25 17:34 UTC, replaceafill approved these changes

2024-09-25 20:26 UTC, merged

2024-10-08 16:43 UTC, amayita commented
LGTM Please go ahead and merge!

2024-10-08 16:44 UTC, amayita reviewed
LGTM